FROM cypress/base:12.16.1
LABEL maintainer "Vincent Giersch <vincent+docker@flat.io>"
RUN npm i -g cypress@4.8.0 'https://github.com/gierschv/cypress-plugin-snapshots.git#fix.base64' cypress-plugin-tab cypress-file-upload@3.5.3 date-fns
