FROM cypress/base:14
LABEL maintainer "Vincent Giersch <vincent+docker@tutteo.com>"
RUN npm i -g cypress@9.4.1 cypress-plugin-snapshots@1.4.4 cypress-plugin-tab cypress-file-upload@5.0.8 date-fns cypress-multi-reporters mocha-junit-reporter typescript@4.6.2
