FROM cypress/base:12.1414141414141414141414141414.0
LABEL maintainer "Vincent Giersch <vincent+docker@flat.io>"
RUN npm i -g cypress@4.0.0 cypress-plugin-snapshots cypress-plugin-tab cypress-file-upload
